
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#153246")


canvas = Canvas(
    window,
    bg = "#153246",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    807.33203125,
    424.6669921875,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    174.33203125,
    426.666015625,
    image=image_image_3
)

canvas.create_text(
    55.33203125,
    224.666015625,
    anchor="nw",
    text="Scan the QR\ncode and sign\nthe waiver\nonce inside",
    fill="#FBFBF3",
    font=("MontserratRoman Regular", 33 * -1)
)

canvas.create_text(
    71.33203125,
    479.9990234375,
    anchor="nw",
    text="Account",
    fill="#F5F0E6",
    font=("MontserratRoman Medium", 33 * -1)
)

canvas.create_text(
    71.33203125,
    544.666015625,
    anchor="nw",
    text="Waiver",
    fill="#F5F0E6",
    font=("MontserratRoman Medium", 33 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    808.0,
    386.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    252.0,
    507.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    252.0,
    571.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    174.3359375,
    73.333984375,
    image=image_image_7
)

canvas.create_text(
    703.0,
    33.0,
    anchor="nw",
    text="Account",
    fill="#F5F0E6",
    font=("Montserrat", 50 * -1)
)

canvas.create_text(
    95.0,
    33.0,
    anchor="nw",
    text="Status",
    fill="#F5F0E6",
    font=("Montserrat", 50 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=688.0,
    y=590.0,
    width=240.0,
    height=73.3330078125
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    807.0,
    73.0,
    image=image_image_8
)
window.resizable(False, False)
window.mainloop()
