
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#153246")


canvas = Canvas(
    window,
    bg = "#153246",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    639.333984375,
    359.3330078125,
    image=image_image_2
)

canvas.create_text(
    502.0,
    614.0,
    anchor="nw",
    text="Please tap ID to start",
    fill="#F5F0E6",
    font=("Montserrat", 26 * -1)
)

canvas.create_text(
    67.0,
    270.0,
    anchor="nw",
    text="UCSD Makerspace",
    fill="#F5F0E6",
    font=("Montserrat", 113 * -1)
)

canvas.create_text(
    67.0,
    372.6669921875,
    anchor="nw",
    text="Welcome Desk",
    fill="#F5F0E6",
    font=("Montserrat", 73 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    88.0,
    90.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    88.0,
    90.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
