
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\build\assets\frame5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#153246")


canvas = Canvas(
    window,
    bg = "#153246",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    807.33203125,
    426.6669921875,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    807.6640625,
    541.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    807.6640625,
    441.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    807.6640625,
    341.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    807.6640625,
    241.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    174.3359375,
    426.666015625,
    image=image_image_7
)

canvas.create_text(
    56.3359375,
    255.3330078125,
    anchor="nw",
    text="Swipe your ID\nand fill in \nmissing info",
    fill="#F5F0E6",
    font=("Montserrat", 33 * -1)
)

canvas.create_text(
    71.3359375,
    480.0,
    anchor="nw",
    text="Account",
    fill="#F5F0E6",
    font=("MontserratRoman Medium", 33 * -1)
)

canvas.create_text(
    71.3359375,
    544.666015625,
    anchor="nw",
    text="Waiver",
    fill="#F5F0E6",
    font=("MontserratRoman Medium", 33 * -1)
)

canvas.create_text(
    751.0,
    181.0,
    anchor="nw",
    text="First Name",
    fill="#F5F0E6",
    font=("MontserratRoman SemiBold", 20 * -1)
)

canvas.create_text(
    753.0,
    281.0,
    anchor="nw",
    text="Last Name",
    fill="#F5F0E6",
    font=("MontserratRoman SemiBold", 20 * -1)
)

canvas.create_text(
    778.0,
    381.0,
    anchor="nw",
    text="Email",
    fill="#F5F0E6",
    font=("MontserratRoman SemiBold", 20 * -1)
)

canvas.create_text(
    788.0,
    481.0,
    anchor="nw",
    text="PID",
    fill="#F5F0E6",
    font=("MontserratRoman SemiBold", 20 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    252.0,
    507.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    252.0,
    571.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    807.3359375,
    73.333984375,
    image=image_image_10
)

canvas.create_text(
    703.0,
    33.0,
    anchor="nw",
    text="Account",
    fill="#F5F0E6",
    font=("Montserrat", 50 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    174.3359375,
    73.333984375,
    image=image_image_11
)

canvas.create_text(
    95.0,
    33.0,
    anchor="nw",
    text="Status",
    fill="#F5F0E6",
    font=("Montserrat", 50 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=689.0,
    y=590.0,
    width=240.0,
    height=73.3330078125
)
window.resizable(False, False)
window.mainloop()
