
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *

import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\source\repos\Check-In\frames\assets\frame4")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class AccountNoWaiver(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.loadWidgets(controller)
        
    def loadWidgets(self, controller):        
        canvas = Canvas(
            controller,
            bg = "#153246",
            height = 720,
            width = 1280,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.pack(fill="both", expand=True)
        
        image_image_1 = PhotoImage(
            file=Path(relative_to_assets("image_1.png")))
        
        self.photoList.append(image_image_1)
        
        image_1 = canvas.create_image(
            640.0,
            360.0,
            image=image_image_1
        )

        image_image_2 = PhotoImage(
            file=Path(relative_to_assets("image_2.png")))
        
        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(
            807.33203125,
            424.6669921875,
            image=image_image_2
        )

        image_image_3 = PhotoImage(
            file=Path(relative_to_assets("image_3.png")))
        
        self.photoList.append(image_image_3)
        
        image_3 = canvas.create_image(
            174.33203125,
            426.666015625,
            image=image_image_3
        )

        canvas.create_text(
            55.33203125,
            224.666015625,
            anchor="nw",
            text="Scan the QR\ncode and sign\nthe waiver\nonce inside",
            fill="#FBFBF3",
            font=("MontserratRoman Regular", 33 * -1)
        )

        canvas.create_text(
            71.33203125,
            479.9990234375,
            anchor="nw",
            text="Account",
            fill="#F5F0E6",
            font=("MontserratRoman Medium", 33 * -1)
        )

        canvas.create_text(
            71.33203125,
            544.666015625,
            anchor="nw",
            text="Waiver",
            fill="#F5F0E6",
            font=("MontserratRoman Medium", 33 * -1)
        )

        image_image_4 = PhotoImage(
            file=Path(relative_to_assets("image_4.png")))
        
        self.photoList.append(image_image_4)
        
        image_4 = canvas.create_image(
            808.0,
            386.0,
            image=image_image_4
        )

        image_image_5 = PhotoImage(
            file=Path(relative_to_assets("image_5.png")))
        
        self.photoList.append(image_image_5)
        
        image_5 = canvas.create_image(
            252.0,
            507.0,
            image=image_image_5
        )

        image_image_6 = PhotoImage(
           file=Path(relative_to_assets("image_6.png")))
        
        self.photoList.append(image_image_6)
        
        image_6 = canvas.create_image(
            252.0,
            571.0,
            image=image_image_6
        )

        image_image_7 = PhotoImage(
           file=Path(relative_to_assets("image_7.png")))
        
        self.photoList.append(image_image_7)
        
        image_7 = canvas.create_image(
            174.3359375,
            73.333984375,
            image=image_image_7
        )

        canvas.create_text(
            703.0,
            33.0,
            anchor="nw",
            text="Account",
            fill="#F5F0E6",
            font=("Montserrat", 50 * -1)
        )

        canvas.create_text(
            95.0,
            33.0,
            anchor="nw",
            text="Status",
            fill="#F5F0E6",
            font=("Montserrat", 50 * -1)
        )

        button_image_1 = PhotoImage(
            file=Path(relative_to_assets("button_1.png")))
        
        self.photoList.append(button_image_1)
        
        button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=688.0,
            y=590.0,
            width=240.0,
            height=73.3330078125
        )

        image_image_8 = PhotoImage(
            file=Path(relative_to_assets("image_8.png")))
        
        self.photoList.append(image_image_8)
        
        image_8 = canvas.create_image(
            807.0,
            73.0,
            image=image_image_8
        )