# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import *
from utils import *
from NoAccCheckInOnly import NoAccCheckInOnly
from UserWelcome import UserWelcome
import logging

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/check_in_reason_assets")

REASONS = [
    "Event/Workshop",
    "Tour",
    "Work/Study",
    "Basement Team Meeting",
    "Meeting with Staff",
    "Meeting with Mentor",
    "Meeting with Faculty",
    "Meeting with Community Partner",
]


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


########################################################
# This is the frame where users will manually check in #
########################################################


class CheckInReason(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.check_in_reason = StringVar()
        self.check_in_reason_entry = 0
        self.check_in_row = []

        self.loadWidgets(controller)

    def loadWidgets(self, controller):
        canvas = Canvas(
            self,
            bg="#153246",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(640.0, 360.0, image=image_image_2)

        image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))

        self.photoList.append(image_image_3)

        image_3 = canvas.create_image(640.0, 424.0, image=image_image_3)

        canvas.create_text(
            212.0,
            120.0,
            anchor="nw",
            text="What is the reason for\nyour visit today?",
            fill="#F5F0E6",
            font=("Montserrat", 48 * -1),
            justify="center",
        )

        button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))

        self.photoList.append(button_image_1)

        self.button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.callCheckIn(controller),
            relief="flat",
        )
        self.button_1.place(x=465.0, y=598.0, width=349.0, height=71.0)

        self.check_in_reason.set(REASONS[0])
        self.check_in_reason_entry = OptionMenu(self, self.check_in_reason, *REASONS)
        self.check_in_reason_entry.config(width=40, font=52)
        self.check_in_reason_entry.place(x=420.0, y=412.0)

    def clearEntries(self):
        self.check_in_reason.set(REASONS[0])

    def setCheckInUser(self, row):
        self.check_in_row = row

    def callCheckIn(self, controller):
        self.check_in_row[5] = self.check_in_reason.get()
        self.clearEntries()
        activity_log = global_.sheets.get_activity_db()
        activity_log.append_row(self.check_in_row)
        global_.traffic_light.set_green()
        global_.app.get_frame(UserWelcome).displayName(self.check_in_row[2])
