# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import *
from utils import *
from NoAccCheckInOnly import NoAccCheckInOnly
from NoAccNoWaiverSwipe import NoAccNoWaiverSwipe
from UserWelcome import UserWelcome
import logging

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/check_in_no_id_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


########################################################
# This is the frame where users will manually check in #
########################################################


class CheckInNoId(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.pid = StringVar()
        self.pid_entry = 0

        self.loadWidgets(controller)

    def loadWidgets(self, controller):
        canvas = Canvas(
            self,
            bg="#153246",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(640.0, 360.0, image=image_image_2)

        image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))

        self.photoList.append(image_image_3)

        image_3 = canvas.create_image(640.0, 424.0, image=image_image_3)

        canvas.create_text(
            212.0,
            120.0,
            anchor="nw",
            text="If you have already made an\naccount, scan your UCSD barcode\nor enter your PID manually",
            fill="#F5F0E6",
            font=("Montserrat", 48 * -1),
            justify="center",
        )

        canvas.create_text(
            605.0,
            480.0,
            anchor="nw",
            text="PID",
            fill="#F5F0E6",
            font=("Montserrat", 24 * -1),
        )

        button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))

        self.photoList.append(button_image_1)

        self.button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.callCheckIn(controller),
            relief="flat",
        )
        self.button_1.place(x=465.0, y=598.0, width=349.0, height=71.0)
        self.bind("<Return>", lambda: self.callCheckIn(controller))

        self.pid_entry = Entry(self, textvariable=self.pid, width=40, font=52)
        self.pid_entry.place(x=420.0, y=412.0)

    def clearEntries(self):
        self.pid_entry.delete(0, END)

    def updateEntries(self, pid):
        self.pid_entry.insert(0, pid)

    def callCheckIn(self, controller):
        pid = self.pid_entry.get()
        entered_pid = pid.lstrip("Aa").lower()
        if not pid:
            return

        util = utils()
        self.clearEntries()

        with open("assets/local_user_db.json", "r", encoding="utf-8") as f:
            user_data = json.load(f)

        curr_user = None
        for uuid, data in user_data.items():
            student_id = data.get("Student ID", "").lstrip("Aa").lower()
            if student_id == entered_pid:
                curr_user = data
                break
        if not curr_user:
            logging.info("Manual check in user account was not found")
            controller.show_frame(NoAccCheckInOnly)
            controller.after(5000, lambda: controller.show_frame(MainPage))
            return
    
        waiver_status = curr_user.get("Waiver Signed", "").strip().lower()

        if waiver_status != "true":
            waiver_data = global_.sheets.get_waiver_db_data()
            if utils.check_waiver_match(self, curr_user, waiver_data):
                logging.info("Updating local waiver status for " + curr_user["Name"])
                curr_user["Waiver Signed"] = "true"
                with open("assets/local_user_db.json", "w", encoding="utf-8") as f:
                    json.dump(user_data, f, indent=2)
            else:
                logging.info("No online waiver found for " + curr_user["Name"])
                controller.show_frame(AccNoWaiver)
                controller.after(3000, lambda: controller.show_frame(NoAccNoWaiverSwipe))
                return
        
        logging.info(f"Checking in with no ID for {curr_user['Name']} at " + util.getDatetime())
        new_row = [
            util.getDatetime(),
            int(time.time()),
            curr_user["Name"],
            "No ID",
            "User Check-in",
            "Main Check-in",
            curr_user["firstEnrTrm"],
            curr_user["lastEnrTrm"],
        ]

        global_.checkin_logger.enqueue_row(new_row, entered_pid)
        global_.traffic_light.set_green()
        global_.app.get_frame(UserWelcome).displayName(curr_user["Name"])
