# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import *
import json


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/main_page_assets")
UPCOMING_EVENTS_PATH = OUTPUT_PATH / "upcoming_events.json"


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class MainPage(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self._events_refresh_job = None
        self.loadWidgets(controller)

    def create_rounded_rect(self, canvas, x1, y1, x2, y2, radius=28, **kwargs):
        points = [
            x1 + radius, y1,
            x1 + radius, y1,
            x2 - radius, y1,
            x2 - radius, y1,
            x2, y1,
            x2, y1 + radius,
            x2, y1 + radius,
            x2, y2 - radius,
            x2, y2 - radius,
            x2, y2,
            x2 - radius, y2,
            x2 - radius, y2,
            x1 + radius, y2,
            x1 + radius, y2,
            x1, y2,
            x1, y2 - radius,
            x1, y2 - radius,
            x1, y1 + radius,
            x1, y1 + radius,
            x1, y1,
        ]
        return canvas.create_polygon(
            points,
            smooth=True,
            splinesteps=20,
            **kwargs
        )

    def load_upcoming_events(self):
        try:
            if not UPCOMING_EVENTS_PATH.exists():
                return []

            payload = json.loads(UPCOMING_EVENTS_PATH.read_text(encoding="utf-8"))
            items = payload.get("items", [])

            cleaned = []
            for item in items[:3]:
                date_label = str(item.get("date_label", "")).strip()
                time_label = str(item.get("time_label", "")).strip()
                text = str(item.get("text", "")).strip()

                if text:
                    cleaned.append(
                        {
                            "date_label": date_label,
                            "time_label": time_label,
                            "text": text,
                        }
                    )

            return cleaned
        except Exception:
            return []

    def render_upcoming_card(self, canvas):
        canvas.delete("upcoming_card")

        OFF_WHITE = "#F5F0E6"
        NAVY = "#153246"
        UCSD_BLUE = "#00629B"
        SOFT_CYAN = "#BFEFFF"
        SOFT_PINK = "#FFE0EC"
        PINK = "#F4B6D2"
        PALE_BLUE = "#DCECF8"

        x1, y1, x2, y2 = 92, 260, 1188, 620
        radius = 34

        # Static glow
        self.create_rounded_rect(
            canvas,
            x1 - 8, y1 - 8, x2 + 8, y2 + 8,
            radius=radius + 6,
            fill="",
            outline=SOFT_PINK,
            width=3,
            tags=("upcoming_card",),
        )
        self.create_rounded_rect(
            canvas,
            x1 - 3, y1 - 3, x2 + 3, y2 + 3,
            radius=radius + 2,
            fill="",
            outline=SOFT_CYAN,
            width=2,
            tags=("upcoming_card",),
        )

        # Main card
        self.create_rounded_rect(
            canvas,
            x1, y1, x2, y2,
            radius=radius,
            fill=OFF_WHITE,
            outline=OFF_WHITE,
            width=2,
            tags=("upcoming_card",),
        )

        # Header pill
        self.create_rounded_rect(
            canvas,
            x1 + 34, y1 + 28, x1 + 415, y1 + 90,
            radius=22,
            fill=PINK,
            outline=PINK,
            width=1,
            tags=("upcoming_card",),
        )
        canvas.create_text(
            x1 + 66,
            y1 + 48,
            anchor="nw",
            text="UPCOMING IN SANDBOX",
            fill=NAVY,
            font=("Inter", 28 * -1, "bold"),
            tags=("upcoming_card",),
        )

        # Small label pill
        self.create_rounded_rect(
            canvas,
            x2 - 220, y1 + 34, x2 - 36, y1 + 78,
            radius=16,
            fill=PALE_BLUE,
            outline=PALE_BLUE,
            width=1,
            tags=("upcoming_card",),
        )
        canvas.create_text(
            x2 - 128,
            y1 + 56,
            anchor="center",
            text="NEXT 10 DAYS",
            fill=UCSD_BLUE,
            font=("Inter", 14 * -1, "bold"),
            tags=("upcoming_card",),
        )

        items = self.load_upcoming_events()

        if not items:
            canvas.create_text(
                640,
                438,
                anchor="center",
                text="No special bookings or closures in the next 10 days.",
                fill=NAVY,
                font=("Inter", 28 * -1),
                tags=("upcoming_card",),
            )
            return

        top_y = y1 + 118
        row_gap = 86
        row_width = (x2 - x1) - 88

        for index, item in enumerate(items):
            row_top = top_y + (index * row_gap)

            canvas.create_text(
                x1 + 44,
                row_top,
                anchor="nw",
                text=f"{item['date_label']}  •  {item['time_label']}",
                fill=UCSD_BLUE,
                font=("Inter", 22 * -1, "bold"),
                tags=("upcoming_card",),
            )

            canvas.create_text(
                x1 + 44,
                row_top + 34,
                anchor="nw",
                text=item["text"],
                fill=NAVY,
                font=("Inter", 25 * -1),
                width=row_width,
                tags=("upcoming_card",),
            )

            if index < len(items) - 1:
                line_y = row_top + 70
                canvas.create_line(
                    x1 + 40, line_y, x2 - 40, line_y,
                    fill=UCSD_BLUE,
                    width=2,
                    tags=("upcoming_card",),
                )

    def schedule_upcoming_card_refresh(self, canvas):
        def refresh():
            self.render_upcoming_card(canvas)
            self._events_refresh_job = self.after(300000, refresh)  # 5 min

        if self._events_refresh_job is None:
            self._events_refresh_job = self.after(300000, refresh)

    def loadWidgets(self, controller):
        from QRCodes import QRCodes
        from CheckInNoId import CheckInNoId

        canvas = Canvas(
            self,
            bg="#153246",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )
        canvas.place(x=0, y=0)

        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
        self.photoList.append(image_image_1)
        canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
        self.photoList.append(image_image_2)
        canvas.create_image(639.333984375, 359.333984375, image=image_image_2)

        canvas.create_text(
            67.0,
            140.0,
            anchor="nw",
            text="SCRIPPS SANDBOX",
            fill="#F5F0E6",
            font=("Refrigerator Deluxe", 92 * -1, "bold"),
        )

        self.render_upcoming_card(canvas)
        self.schedule_upcoming_card_refresh(canvas)

        canvas.create_text(
            640.0,
            682.0,
            anchor="center",
            text="Tap ID on the black box to start",
            fill="#F5F0E6",
            font=("Inter", 22 * -1, "bold"),
        )

        image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
        self.photoList.append(image_image_3)
        canvas.create_image(88.0, 90.0, image=image_image_3)

        button_image_1 = PhotoImage(file=relative_to_assets("image_4.png"))
        self.photoList.append(button_image_1)

        button_1 = Button(
            self,
            image=button_image_1,
            bg="#153246",
            activebackground="#153246",
            command=lambda: controller.show_frame(QRCodes),
            relief="flat",
            highlightthickness=0,
            bd=0,
        )
        button_1.place(x=53.0, y=55.0)

        button_2 = Button(
            self,
            image=image_image_3,
            text="No\nID",
            compound="center",
            bg="#153246",
            activebackground="#153246",
            fg="white",
            command=lambda: controller.show_frame(CheckInNoId),
            relief="flat",
            highlightthickness=0,
            bd=0,
            font=("Inter", 36 * -1),
        )
        button_2.place(x=1130.0, y=40.0)
