
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\source\repos\Check-In\frames\assets\mainpage")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class MainPage(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        
        print(type(self))
                                               
        canvas = Canvas(
            controller,
            bg = "#153246",
            height = 720,
            width = 1280,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        #canvas.place(x = 0, y = 0)
        canvas.pack(fill="both", expand=True)
        
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        
        self.image_1 = canvas.create_image(
            640.0,
            360.0,
            image=image_image_1
        )

        """
        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        self.image_2 = self.canvas.create_image(
            639.333984375,
            359.3330078125,
            image=image_image_2
        )

        self.canvas.create_text(
            502.0,
            614.0,
            anchor="nw",
            text="Please tap ID to start",
            fill="#F5F0E6",
            font=("Montserrat", 26 * -1)
        )

        self.canvas.create_text(
            67.0,
            270.0,
            anchor="nw",
            text="UCSD Makerspace",
            fill="#F5F0E6",
            font=("Montserrat", 113 * -1)
        )

        self.canvas.create_text(
            67.0,
            372.6669921875,
            anchor="nw",
            text="Welcome Desk",
            fill="#F5F0E6",
            font=("Montserrat", 73 * -1)
        )

        image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        self.image_3 = self.canvas.create_image(
            88.0,
            90.0,
            image=image_image_3
        )

        image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        self.image_4 = self.canvas.create_image(
            88.0,
            90.0,
            image=image_image_4
        )
        """
