
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\logan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\build\assets\frame9")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#153246")


canvas = Canvas(
    window,
    bg = "#153246",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    640.0,
    76.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    640.0,
    430.0,
    image=image_image_3
)

canvas.create_text(
    371.0,
    45.0,
    anchor="nw",
    text="Account",
    fill="#F5F0E6",
    font=("MontserratRoman Regular", 40 * -1)
)

canvas.create_text(
    701.0,
    45.0,
    anchor="nw",
    text="Waiver",
    fill="#F5F0E6",
    font=("MontserratRoman Regular", 40 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    585.0,
    77.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    884.0,
    77.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    640.0,
    542.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    640.0,
    440.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    640.0,
    339.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    640.0,
    239.0,
    image=image_image_9
)

canvas.create_text(
    501.0,
    177.0,
    anchor="nw",
    text="First Name",
    fill="#F5F0E6",
    font=("MontserratRoman Light", 24 * -1)
)

canvas.create_text(
    503.0,
    278.0,
    anchor="nw",
    text="Last Name",
    fill="#F5F0E6",
    font=("MontserratRoman Light", 24 * -1)
)

canvas.create_text(
    566.0,
    379.0,
    anchor="nw",
    text="Email",
    fill="#F5F0E6",
    font=("MontserratRoman Light", 24 * -1)
)

canvas.create_text(
    594.0,
    480.0,
    anchor="nw",
    text="PID",
    fill="#F5F0E6",
    font=("MontserratRoman Light", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=465.0,
    y=598.0,
    width=349.0,
    height=71.0
)
window.resizable(False, False)
window.mainloop()
