# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
from gui import *
import global_
import logging

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/no_acc_swipe_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def go_to_manual_fill(controller):
    logging.info("Going to manual fill")
    global_.app.get_frame(ManualFill).clearEntries()
    controller.show_frame(ManualFill)


class NoAccSwipe(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.loadWidgets(controller)

    def loadWidgets(self, controller):
        canvas = Canvas(
            self,
            bg="#153246",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(640.0, 76.0, image=image_image_2)

        image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))

        self.photoList.append(image_image_3)

        image_3 = canvas.create_image(640.0, 430.0, image=image_image_3)

        canvas.create_text(
            315.0,
            350.0,
            anchor="nw",
            text="Please scan your ID barcode",
            fill="#F5F0E6",
            font=("Montserrat", 48 * -1),
        )

        canvas.create_text(
            445.0,
            55.0,
            anchor="nw",
            text="Account Status:",
            fill="#F5F0E6",
            font=("Montserrat", 40 * -1),
        )

        image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))

        self.photoList.append(image_image_4)

        image_4 = canvas.create_image(797.0, 75.0, image=image_image_4)

        button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))

        self.photoList.append(button_image_1)

        button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: go_to_manual_fill(controller),
            relief="flat",
        )
        button_1.place(x=465.0, y=554.0, width=349.0, height=71.0)
