# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
from ManualFill import ManualFill
import global_
import CheckInNoId

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/no_acc_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class NoAccCheckInOnly(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.loadWidgets(controller)

    def loadWidgets(self, controller):
        canvas = Canvas(
            self,
            bg="#153244",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = canvas.create_image(639.333984375, 359.333984375, image=image_image_2)

        canvas.create_text(
            160.0,
            180.0,
            anchor="nw",
            text="Looks like you don't have an\n account linked to this PID.\nWould you like to:",
            fill="#F5F0E6",
            font=("Montserrat", 64 * -1),
        )

        # Create new account button
        button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
        self.photoList.append(button_image_1)

        button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.go_to_manual_fill(controller),
            relief="flat",
        )
        button_1.place(x=465.0, y=400.0, width=349.0, height=71.0)

        # Link existing account button
        button_image_2 = PhotoImage(file=relative_to_assets("button_1.png"))
        self.photoList.append(button_image_2)

        button_2 = Button(
            self,
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.go_to_check_in_no_id(controller),
            relief="flat",
        )
        button_2.place(x=465.0, y=500.0, width=349.0, height=71.0)

        # Add text labels for buttons
        canvas.create_text(
            500.0,
            430.0,
            anchor="nw",
            text="Create New Account",
            fill="#F5F0E6",
            font=("Montserrat", 24 * -1),
        )

        canvas.create_text(
            500.0,
            530.0,
            anchor="nw",
            text="Link Existing Account",
            fill="#F5F0E6",
            font=("Montserrat", 24 * -1),
        )

    def go_to_manual_fill(self, controller):
        global_.app.get_frame(ManualFill).clearEntries()
        controller.show_frame(ManualFill)

    def go_to_check_in_no_id(self, controller):
        global_.app.get_frame(CheckInNoId.CheckInNoId).clearEntries()
        controller.show_frame(CheckInNoId.CheckInNoId)
