# Part of this file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
from MainPage import *
import time
import global_

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/user_welcome_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def back_to_main():
    global_.traffic_light.set_off()
    global_.app.show_frame(MainPage)


class UserWelcome(Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.photoList = []
        self.loadWidgets(controller)
        self.offset = 0

    def loadWidgets(self, controller):
        self.canvas = Canvas(
            self,
            bg="#153244",
            height=720,
            width=1280,
            bd=0,
            highlightthickness=0,
            relief="ridge",
        )

        self.canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))

        self.photoList.append(image_image_1)

        image_1 = self.canvas.create_image(640.0, 360.0, image=image_image_1)

        image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))

        self.photoList.append(image_image_2)

        image_2 = self.canvas.create_image(
            639.333984375, 359.333984375, image=image_image_2
        )

        self.canvas.create_text(
            99.33203125,
            259.33203125,
            anchor="nw",
            text="Welcome back",
            fill="#F5F0E6",
            font=("Montserrat", 45 * -1),
        )

    def removeName(self, text_id):
        self.canvas.delete(text_id)
        self.offset -= 73

        # Move the remaining text objects up
        for text in self.canvas.find_withtag("welcome"):
            coords = self.canvas.coords(text)
            if coords[1] > 323.0:
                self.canvas.move(text, 0, -73)

        # Check if there are any remaining "welcome" text objects
        if not self.canvas.find_withtag("welcome"):
            back_to_main()

    def displayName(self, name):
        text_id = self.canvas.create_text(
            99.0,
            323.0 + self.offset,
            anchor="nw",
            text=name,
            fill="#F5F0E6",
            font=("Montserrat", 73 * -1),
            tag=f"welcome",
        )

        self.offset += 73
        global_.app.show_frame(UserWelcome)
        self.canvas.after(3000, lambda: self.removeName(text_id))
